language: python
python:
  - "2.7"
  - "3.3"
  - pypy

install:
  - "pip install ."
  - "pip install -r test_requirements.txt"
script:
  - >
      if [[ $TRAVIS_PYTHON_VERSION == pypy ]]; then
        py.test test/
      else
        py.test -n 4 --cov hyper test/
        coverage report -m --fail-under 100
      fi
